name: etl-incremental
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run incremental ETL
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_REGISTRY: ${{ secrets.NOTION_DB_REGISTRY }}
          NOTION_DB_CASES: ${{ secrets.NOTION_DB_CASES }}
          NOTION_DB_PUBLISHING: ${{ secrets.NOTION_DB_PUBLISHING }}
          NOTION_DB_FINANCE: ${{ secrets.NOTION_DB_FINANCE }}
          PG_DSN: ${{ secrets.PG_DSN }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET: traceremove-content
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          EMBEDDINGS_MODEL: text-embedding-3-large
          PUBLIC_MODE: 'true'
        run: |
          source .venv/bin/activate
          python -m etl.main
